apiVersion: v1
kind: Service
metadata:
  name: serviciu-daune
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '5003'
spec:
  selector:
    app: serviciu-daune
  ports:
    - protocol: TCP
      port: 83
      targetPort: 5003
  type: ClusterIP
