apiVersion: v1
kind: Service
metadata:
  name: serviciu-baza-de-date-polite
spec:
  selector:
    app: serviciu-baza-de-date-polite
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
