apiVersion: v1
kind: Service
metadata:
  name: serviciu-baza-de-date-polite
spec:
  selector:
    app: serviciu-baza-de-date-polite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
