apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciu-clienti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviciu-clienti
  template:
    metadata:
      labels:
        app: serviciu-clienti
    spec:
      containers:
        - name: serviciu-clienti
          image: alexpraf/serviciu_clienti:latest 
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTION_CLIENTI
              value: "postgresql://user_clienti:clienti123@serviciu-baza-de-date-clienti:5432/db_clienti"
          ports:
            - containerPort: 5000
