apiVersion: v1
kind: Service
metadata:
  name: serviciu-clienti
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '5000'
spec:
  selector:
    app: serviciu-clienti
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
