apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciu-plati
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviciu-plati
  template:
    metadata:
      labels:
        app: serviciu-plati
    spec:
      containers:
        - name: serviciu-plati
          image: alexpraf/serviciu_plati:latest 
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTION_PLATI
              value: "postgresql://user_plati:plati123@serviciu-baza-de-date-plati:5432/db_plati"
          ports:
            - containerPort: 5002
