apiVersion: v1
kind: Service
metadata:
  name: serviciu-plati
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '5002'
spec:
  selector:
    app: serviciu-plati
  ports:
    - protocol: TCP
      port: 82
      targetPort: 5002
  type: ClusterIP
