apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciu-baza-de-date-plati
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serviciu-baza-de-date-plati
  template:
    metadata:
      labels:
        app: serviciu-baza-de-date-plati
    spec:
      containers:
        - name: serviciu-baza-de-date-plati
          image: alexpraf/serviciu_baza_de_date_plati:latest
          ports:
            - containerPort: 5000
