apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-script-plati
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS insurance_payments (
    id SERIAL PRIMARY KEY,
    id_policy INTEGER NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciu-baza-de-date-plati
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: serviciu-baza-de-date-plati
  template:
    metadata:
      labels:
        app: serviciu-baza-de-date-plati
    spec:
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_PASSWORD
              value: plati123
            - name: POSTGRES_USER
              value: user_plati
            - name: POSTGRES_DB
              value: db_plati
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata-plati
              mountPath: /var/lib/postgresql/data
            - name: init-sql-script-plati
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pgdata-plati
          emptyDir: {}
        - name: init-sql-script-plati
          configMap:
            name: init-sql-script-plati
