apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciu-polite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviciu-polite
  template:
    metadata:
      labels:
        app: serviciu-polite
    spec:
      containers:
        - name: serviciu-polite
          image: alexpraf/serviciu_polite:latest
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTION_POLITE
              value: "postgresql://user_polite:polite123@serviciu-baza-de-date-polite:5432/db_polite"
            - name: PROMETHEUS_MULTIPROC_DIR
              value: "/tmp"
          ports:
            - containerPort: 5001
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.15.1
          volumeMounts:
            - name: logstash-config
              mountPath: /tmp/logstash/pipeline/
          ports:
            - containerPort: 5044
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
