apiVersion: v1
kind: Service
metadata:
  name: serviciu-polite
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '5001'
spec:
  selector:
    app: serviciu-polite
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5001
  type: LoadBalancer
