apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk-stack
  template:
    metadata:
      labels:
        app: elk-stack
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
          ports:
            - containerPort: 9200
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.15.1
          ports:
            - containerPort: 5601
